id: 'dimmer'
alias: Dimmer
initial_state: 'on'
trigger:
  - platform: state
    entity_id: event.hue_dimmer_action
    to: ~
action:
  - service: notify.send_message
    target: 
      entity_id: notify.debug_log
    data:
      message: "The following button was pressed: {{ trigger.to_state.attributes.event_type }} - {{ trigger.to_state.attributes.action }}"
