id: 'car_update_myskoda'
alias: 'Car update for MySkoda'
initial_state: 'on'
triggers:
  - trigger: state
    entity_id: binary_sensor.pixel_xl_android_auto
    to: ~
    for: '00:01:00'
    id: 'auto'
actions:
  - action: homeassistant.update_entity
    data:
      entity_id:
        - device_tracker.skoda_superb_combi_position

