id: 'office_dial_action'
initial_state: 'on'
alias: 'Office dial action'
triggers:
  - trigger: state
    entity_id: event.office_dial_moes_action
    to: ~
    id: event
conditions:
  - condition: template
    value_template: >-
      {{ trigger.to_state.attributes.event_type == 'toggle' }}
actions:
  - if:
      - condition: state
        entity_id: media_player.office
        state: 'playing'
    then:
      - action: media_player.media_pause
        data:
          entity_id: media_player.office
    else:
      - action: media_player.media_play
        data:
          entity_id: media_player.office
