id: 'office_dial_rotate'
initial_state: 'on'
alias: 'Office dial rotate'
triggers:
  - trigger: state
    entity_id: event.office_dial_moes_action
    to: ~
    id: event
conditions:
  - condition: template
    value_template: >-
      {{ trigger.to_state.attributes.event_type in ['brightness_step','brightness_step','color_temperature_step_up','color_temperature_step_down'] }}
variables:
  action: >-
    {{ 'volume_'+trigger.to_state.attributes.direction if trigger.to_state.attributes.event_type == 'brightness_step' else ('next_track' if trigger.to_state.attributes.event_type == 'color_temperature_step_up' else 'prev_track') }}
  current_vol: "{{ state_attr('media_player.office','volume_level')|float(0) }}"
  vol_step: "{{ (trigger.to_state.attributes.action_step_size|float(12)/1000)|round(2) }}"
  new_vol: >-
    {{ (min(1,(current_vol|float(0)+vol_step|float(0))))|round(2) if (trigger.id == 'volume_up' or (trigger.to_state.attributes.event_type == 'brightness_step' and trigger.to_state.attributes.direction == 'up')) else (max(0,(current_vol|float(0)-vol_step|float(0))))|round(2) }}
action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ action == 'volume_up' or action == 'volume_down'}}"
      sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.office
          volume_level: "{{ new_vol }}"
    - conditions:
      - condition: template
        value_template: "{{ action == 'next_track' }}"
      sequence:
      - service: media_player.media_play
        data:
          entity_id: media_player.office
      - service: media_player.media_next_track
        data:
          entity_id: media_player.office
    - conditions:
      - condition: template
        value_template: "{{ action == 'prev_track' }}"
      sequence:
      - service: media_player.media_play
        data:
          entity_id: media_player.office
      - service: media_player.media_previous_track
        data:
          entity_id: media_player.office
