id: 'office_dial_action'
initial_state: 'on'
alias: 'Office dial action'
trigger:
  - platform: state
    entity_id: event.office_dial_moes_action
    to: ~
    id: event
action:
  - choose:
    - conditions:
      - condition: trigger
        id: 'toggle'
      - condition: state
        entity_id: media_player.office
        state: 'playing'
      sequence:
      - service: media_player.media_pause
        data:
          entity_id: media_player.office
    - conditions:
      - condition: trigger
        id: 'toggle'
      sequence:
      - service: media_player.media_play
        data:
          entity_id: media_player.office
    - conditions:
      - condition: trigger
        id: 'event'
      - condition: template
        value_template: >-
          {{ trigger.to_state.attributes.event_type == 'toggle' }}
      - condition: state
        entity_id: media_player.office
        state: 'playing'
      sequence:
      - service: media_player.media_pause
        data:
          entity_id: media_player.office
    - conditions:
      - condition: trigger
        id: 'event'
      - condition: template
        value_template: >-
          {{ trigger.to_state.attributes.event_type == 'toggle' }}
      sequence:
      - service: media_player.media_play
        data:
          entity_id: media_player.office
