id: 'office_dial_test'
alias: 'Office dial test'
trigger:
  - platform: state
    entity_id: event.office_dial_moes_action
    to: ~
action:
  - service: notify.send_message
    target: 
      entity_id: notify.debug_log
    data:
      message: >-
        Office dial from {{ trigger.from_state.attributes.event_type }}/{{ trigger.from_state.attributes.direction }} to {{ trigger.to_state.attributes.event_type }}/{{ trigger.to_state.attributes.direction }}
