id: 'adults_away_something_open'
alias: 'Adults away something open'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: 
      - input_boolean.adults_away
      - input_boolean.all_away
    from: 'off'
    to: 'on'
condition:
  # We haven't just returned and left again
  - "{{ (now()-trigger.from_state.last_changed).seconds > 300 }}"
  # And something is currently open
  - condition: or
    conditions:
    - condition: state
      entity_id: group.my_exterior_doors
      state: 'on'
    - condition: state
      entity_id: group.my_downstairs_windows
      state: 'on'
    - condition: and
      conditions:
        # Upstairs are open and everybody is away
        - condition: state
          entity_id: 
            - group.my_upstairs_windows
            - input_boolean.all_away
          state: 'on'
action:
  # Notify the last person to leave
  - if:
      - condition: template
        value_template: >-
          {{ as_timestamp(states.input_boolean.person2_home.last_updated) > as_timestamp(states.input_boolean.person3_home.last_updated) }}
    then:
      - if:
          - condition: state
            entity_id: binary_sensor.pixel_xl_android_auto
            state: 'on'
        then:
          - action: notify.mobile_app_pixel_xl
            data:
              title: >-
                {{ expand(['group.my_downstairs_windows', 'group.my_upstairs_windows', 'group.my_exterior_doors'])|selectattr('state', 'eq', 'on')|list|length }} things are open
              message: >-
                The following are open: {{ expand(['group.my_downstairs_windows', 'group.my_upstairs_windows', 'group.my_exterior_doors'])|selectattr('state', 'eq', 'on')|map(attribute='name')|list|join(', ')  }}
              data:
                car_ui: true
                notification_icon: "mdi:shield-home"
                channel: "car"
                importance: high
        else:
          - action: notify.person2
            data:
              message: >-
                The following are open: {{ expand(['group.my_downstairs_windows', 'group.my_upstairs_windows', 'group.my_exterior_doors'])|selectattr('state', 'eq', 'on')|map(attribute='name')|list|join(', ')  }}
    else:
      - action: notify.person3
        data: 
          message: >-
            The following are open: {{ expand(['group.my_downstairs_windows', 'group.my_upstairs_windows', 'group.my_exterior_doors'])|selectattr('state', 'eq', 'on')|map(attribute='name')|list|join(', ')  }}
